/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DBITTestContract } from "./DBITTest";
import { DNFTContract } from "./DNFT";
import { DNFT2Contract } from "./DNFT2";
import { DNFT3Contract } from "./DNFT3";
import { ERC165Contract } from "./ERC165";
import { ERC721Contract } from "./ERC721";
import { IDNFTContract } from "./IDNFT";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC721Contract } from "./IERC721";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { IPseudoRandomContract } from "./IPseudoRandom";
import { LinkTokenInterfaceContract } from "./LinkTokenInterface";
import { MysteryBoxTestContract } from "./MysteryBoxTest";
import { PseudoRandomContract } from "./PseudoRandom";
import { RandomNumberContract } from "./RandomNumber";
import { VRFConsumerBaseContract } from "./VRFConsumerBase";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DBITTest"): DBITTestContract;
      require(name: "DNFT"): DNFTContract;
      require(name: "DNFT2"): DNFT2Contract;
      require(name: "DNFT3"): DNFT3Contract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "IDNFT"): IDNFTContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "IPseudoRandom"): IPseudoRandomContract;
      require(name: "LinkTokenInterface"): LinkTokenInterfaceContract;
      require(name: "MysteryBoxTest"): MysteryBoxTestContract;
      require(name: "PseudoRandom"): PseudoRandomContract;
      require(name: "RandomNumber"): RandomNumberContract;
      require(name: "VRFConsumerBase"): VRFConsumerBaseContract;
    }
  }
}

export { DBITTestContract, DBITTestInstance } from "./DBITTest";
export { DNFTContract, DNFTInstance } from "./DNFT";
export { DNFT2Contract, DNFT2Instance } from "./DNFT2";
export { DNFT3Contract, DNFT3Instance } from "./DNFT3";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export { IDNFTContract, IDNFTInstance } from "./IDNFT";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { IPseudoRandomContract, IPseudoRandomInstance } from "./IPseudoRandom";
export {
  LinkTokenInterfaceContract,
  LinkTokenInterfaceInstance,
} from "./LinkTokenInterface";
export {
  MysteryBoxTestContract,
  MysteryBoxTestInstance,
} from "./MysteryBoxTest";
export { PseudoRandomContract, PseudoRandomInstance } from "./PseudoRandom";
export { RandomNumberContract, RandomNumberInstance } from "./RandomNumber";
export {
  VRFConsumerBaseContract,
  VRFConsumerBaseInstance,
} from "./VRFConsumerBase";
