/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { DBITContract } from "./DBIT";
import { DBITTestContract } from "./DBITTest";
import { DebondTokenContract } from "./DebondToken";
import { DNFTContract } from "./DNFT";
import { DNFT0Contract } from "./DNFT0";
import { DNFT1Contract } from "./DNFT1";
import { DNFT2Contract } from "./DNFT2";
import { DNFT3Contract } from "./DNFT3";
import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { ERC721Contract } from "./ERC721";
import { GouvernanceContract } from "./Gouvernance";
import { GovernanceOwnableContract } from "./GovernanceOwnable";
import { IAccessControlContract } from "./IAccessControl";
import { IActivableContract } from "./IActivable";
import { IDebondTokenContract } from "./IDebondToken";
import { IDNFTContract } from "./IDNFT";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { IGovernanceAddressUpdatableContract } from "./IGovernanceAddressUpdatable";
import { IPseudoRandomContract } from "./IPseudoRandom";
import { LinkTokenInterfaceContract } from "./LinkTokenInterface";
import { MigrationsContract } from "./Migrations";
import { MysteryBoxTestContract } from "./MysteryBoxTest";
import { OwnableContract } from "./Ownable";
import { PseudoRandomContract } from "./PseudoRandom";
import { RandomNumberContract } from "./RandomNumber";
import { VRFConsumerBaseContract } from "./VRFConsumerBase";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "DBIT"): DBITContract;
      require(name: "DBITTest"): DBITTestContract;
      require(name: "DebondToken"): DebondTokenContract;
      require(name: "DNFT"): DNFTContract;
      require(name: "DNFT0"): DNFT0Contract;
      require(name: "DNFT1"): DNFT1Contract;
      require(name: "DNFT2"): DNFT2Contract;
      require(name: "DNFT3"): DNFT3Contract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "gouvernance"): GouvernanceContract;
      require(name: "GovernanceOwnable"): GovernanceOwnableContract;
      require(name: "IAccessControl"): IAccessControlContract;
      require(name: "IActivable"): IActivableContract;
      require(name: "IDebondToken"): IDebondTokenContract;
      require(name: "IDNFT"): IDNFTContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(
        name: "IGovernanceAddressUpdatable"
      ): IGovernanceAddressUpdatableContract;
      require(name: "IPseudoRandom"): IPseudoRandomContract;
      require(name: "LinkTokenInterface"): LinkTokenInterfaceContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "MysteryBoxTest"): MysteryBoxTestContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "PseudoRandom"): PseudoRandomContract;
      require(name: "RandomNumber"): RandomNumberContract;
      require(name: "VRFConsumerBase"): VRFConsumerBaseContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export { DBITContract, DBITInstance } from "./DBIT";
export { DBITTestContract, DBITTestInstance } from "./DBITTest";
export { DebondTokenContract, DebondTokenInstance } from "./DebondToken";
export { DNFTContract, DNFTInstance } from "./DNFT";
export { DNFT0Contract, DNFT0Instance } from "./DNFT0";
export { DNFT1Contract, DNFT1Instance } from "./DNFT1";
export { DNFT2Contract, DNFT2Instance } from "./DNFT2";
export { DNFT3Contract, DNFT3Instance } from "./DNFT3";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export { GouvernanceContract, GouvernanceInstance } from "./Gouvernance";
export {
  GovernanceOwnableContract,
  GovernanceOwnableInstance,
} from "./GovernanceOwnable";
export {
  IAccessControlContract,
  IAccessControlInstance,
} from "./IAccessControl";
export { IActivableContract, IActivableInstance } from "./IActivable";
export { IDebondTokenContract, IDebondTokenInstance } from "./IDebondToken";
export { IDNFTContract, IDNFTInstance } from "./IDNFT";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export {
  IGovernanceAddressUpdatableContract,
  IGovernanceAddressUpdatableInstance,
} from "./IGovernanceAddressUpdatable";
export { IPseudoRandomContract, IPseudoRandomInstance } from "./IPseudoRandom";
export {
  LinkTokenInterfaceContract,
  LinkTokenInterfaceInstance,
} from "./LinkTokenInterface";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  MysteryBoxTestContract,
  MysteryBoxTestInstance,
} from "./MysteryBoxTest";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PseudoRandomContract, PseudoRandomInstance } from "./PseudoRandom";
export { RandomNumberContract, RandomNumberInstance } from "./RandomNumber";
export {
  VRFConsumerBaseContract,
  VRFConsumerBaseInstance,
} from "./VRFConsumerBase";
